services:
  postgres:
    image: postgres:17-alpine
    container_name: hono-nextjs-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hono_nextjs
      TZ: UTC
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - type: volume
        source: hono-nextjs-postgres
        target: /var/lib/postgresql/data

volumes:
  hono-nextjs-postgres:
    name: hono-nextjs-postgres
    driver: local
